### ISSUE TITLE
Black Screen In Menus

### ISSUE THREAD

**Issue by MissionWAR** [UltimatChamp/optimum-fuse#41] opened 2024-10-21 20:06 UTC
### Describe your issue

Sometimes, when changing resource packs, the background turns black. However, this doesn't happen all the time, so I'm not sure if it's the actual cause of the bug.

### Modpack version

OptimumFuse 1.12.6+fabric.1.21.1

### Launcher

Modrinth

### Additional context

![2024-10-21_23 05 02](https://github.com/user-attachments/assets/80977531-e0e5-40ff-a18a-cdfbba9c4c55)

**Comment by UltimatChamp** [comment] 2024-11-12 05:43
Closing this as "Can't Reproduce".

**Closed by UltimatChamp** 2024-11-12 05:43 UTC
Labels: 🪲bug
